services:
  alloy: 
    container_name: alloy
    image: grafana/alloy:latest
    restart: unless-stopped
    networks:
      - grafana-monitoring
    ports:
      - "12345:12345"
    volumes:
      - ./configs/config.alloy:/etc/alloy/config.alloy:ro
      - ./data/alloy:/var/lib/alloy/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command: 
      - run 
      - --server.http.listen-addr=0.0.0.0:12345    # Required to access Alloy UI on http://localhost:12345/
      - --storage.path=/var/lib/alloy/data 
      - /etc/alloy/config.alloy

  loki:
    container_name: loki
    user: ${GRAFANA_DOCKER_USER}
    image: grafana/loki:main
    restart: unless-stopped
    networks:
      - grafana-monitoring
    ports:
      - "3100:3100"
    volumes:
      - ./data/loki:/etc/loki
      - ./configs/loki.yml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  prometheus:
    container_name: prometheus
    user: ${GRAFANA_DOCKER_USER}
    image: prom/prometheus
    restart: unless-stopped
    networks:
      - grafana-monitoring
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus/global.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/prometheus/rules/:/etc/prometheus/rules/:ro
      - ./data/prometheus:/prometheus/data
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
      # - --web.enable-admin-api    # Required to clear tombstone files
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 5s
      timeout: 3s
      retries: 5

  mimir:
    container_name: mimir
    image: grafana/mimir-alpine
    networks:
      - grafana-monitoring
    ports:
      - "9009:9009"  # Mimir HTTP port
    volumes:
      - ./configs/mimir-config.yml:/etc/mimir/mimir.yaml:ro
      - ./data/mimir:/data:rw
    command:
      - "-config.file=/etc/mimir/mimir.yaml"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9009/ready"]
      interval: 10s
      timeout: 30s
      retries: 5

  grafana:
    container_name: grafana
    user: ${GRAFANA_DOCKER_USER}
    depends_on: 
      prometheus:
        condition: service_healthy
      mimir:
        condition: service_healthy
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    networks:
      - grafana-monitoring
    ports:
     - 3000:3000/tcp
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./configs/grafana/dashboards-json:/var/lib/grafana/dashboards:ro
      - ./data/grafana:/var/lib/grafana
    environment: 
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
      GF_PROVISIONING_WAIT_TIMEOUT: 60
      LOKI_URL: ${LOKI_URL}

networks:
  grafana-monitoring:
    external: false