{
 "title": "cAdvisor Docker Insights (InfluxDB)",
 "description": "This Grafana dashboard offers a basic overview of key performance metrics for Docker containers in your system.",
 "time": { "from": "2026-02-23T00:00:00.000Z", "to": "2026-02-27T23:59:59.000Z" },
 "refresh": "30s",
 "panels": [
  { "title": "Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"container_last_seen\" and r.name != \"\")\n  |> group()\n  |> distinct(column: \"name\")\n  |> count()"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "cpuUsageRate = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"container_cpu_usage_seconds_total\")\n  |> filter(fn: (r) => exists r.name)\n  |> increase()\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> derivative()\n\ntotalCPUCoresRecord = from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"machine_cpu_cores\")\n  |> last()\n  |> findRecord(fn: (key) => true, idx: 0)\n\ntotalCPUCores = totalCPUCoresRecord._value\n\ncpuUsageRate\n  |> map(fn: (r) => ({\n      _time: r._time,\n      name: r.name,\n      _value: (r._value / totalCPUCores) * 100.0\n    }))\n  |> yield(name: \"cpu_usage_percentage\")"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"container_memory_usage_bytes\")\n  |> filter(fn: (r) => exists r.name)\n  |> group(columns: [\"name\"])\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\n  |> yield(name: \"raw_values\")"
    }
   ]
  },
  {
   "title": "Memory Cached",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"container_memory_cache\")\n  |> filter(fn: (r) => exists r.name)\n  |> group(columns: [\"name\"])\n  |> keep(columns: [\"_time\", \"_value\", \"name\"])\n  |> yield(name: \"raw_values\")"
    }
   ]
  },
  { "title": "I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{name=~\".+\"}[10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Writes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{name=~\".+\"}[10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[10m])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Container Heartbeat",
   "type": "heatmap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "query": "from(bucket: \"telegraf\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus_remote_write\")\n  |> filter(fn: (r) => r._field == \"container_last_seen\")\n  |> filter(fn: (r) => exists r.name)\n  |> difference()\n  |> aggregateWindow(every: 1m, fn: count, createEmpty: false)\n  |> aggregateWindow(every: 1m, period: 5m, fn: count)\n  |> rename(columns: {_value: \"bpm\"})\n  |> group(columns: [\"name\"])"
    }
   ]
  }
 ]
}