# Read metrics about docker containers

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 10000
  metric_buffer_limit = 100000
  flush_interval = "20s"
  flush_jitter = "5s"
  collection_jitter = "2s"
  omit_hostname = false
  skip_processors_after_aggregators = true

[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]             
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
  timeout = "15s"
  content_encoding = "gzip"
  metric_batch_size = 10000
  metric_buffer_limit = 5000
  flush_interval = "5s"

[[inputs.http_listener_v2]]
  service_address = ":1234"          # Port Telegraf listens on
  paths = ["/receive"]
  methods = ["POST", "PUT"]          # Prometheus uses POST
  data_format = "prometheusremotewrite"
  read_timeout = "10s"
  write_timeout = "10s"
  max_body_size = "64MB"
  http_headers = {"Connection" = "keep-alive"}

[inputs.http_listener_v2.tags]
  listener = "prometheus_metrics"