[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 5000
  metric_buffer_limit = 25000
  debug = true

[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]             
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"
  timeout = "30s"
  content_encoding = "gzip"

[[inputs.http_listener_v2]]
  service_address = ":9273"
  paths = ["/metrics"]
  data_format = "prometheusremotewrite"
