# Read metrics about docker containers

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "10s"
  hostname = ""
  omit_hostname = false
  skip_processors_after_aggregators = true

[[outputs.influxdb_v2]]
  urls = ["$INFLUX_URL"]        # NOTE: verify, could be 9999 if using OSS Beta
  token = "$INFLUX_TOKEN"
  organization = "$INFLUX_ORG"
  bucket = "$INFLUX_BUCKET"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"

  # Per-container metrics
  perdevice_include = [
    "cpu",
    "blkio",
    "network",
    # "memory",
    # "healthcheck"
  ]
  
  # Aggregate metrics
  total_include = [
    "cpu", 
    "blkio",
    "network"
    # "memory",
  ]
  
  # Filter containers

  container_name_include = []
  container_name_exclude = []
  container_state_include = ["running"]

